"""Die Mutantenliste (maschinell erzeugt von tools/gen_mutants.py, Literal): (Modul, alte Stelle, neue Stelle), jede alte Stelle kommt im Modul genau einmal vor.
Gleichwertige Mutanten (Darstellung ohne Verhaltensänderung, Gleichheit von Gleitkommazahlen) stehen in EQUIVALENT_NOTES."""
EQUIVALENT_NOTES = """Stand nach drei Läufen: 812 Mutanten, davon 753 von den Tests gefunden, 59 überlebend (beim Lauf 3 gegen die Tests mit test_gaps_round2.py). Die 59 wurden einzeln angesehen und nach
Verhalten in vier Gruppen sortiert (die Einordnung ist eine Einschätzung, kein Beweis der Gleichwertigkeit):
(1) Vergleich am Maßnullpunkt: '<' gegen '<=' (und '>' gegen '>=') an einer Stelle, an der beide Seiten nur bei exakter Gleichheit von Gleitkommazahlen verschieden entscheiden
    (Kosten-Differenzen, Bestand gegen Schwelle, Ladung gegen Q + 1e-9, Toleranz 1e-9). Solche Gleichheit tritt bei den echten Instanzen nicht auf; ein künstlich erzeugter Gleichstand
    würde nur den Zufall des Rundens prüfen.
(2) Verschiebungen in Grenzen von Schleifen, die keine Wirkung haben: range(n+1) statt range(n-1) in der 2-opt-Schleife (leere innere Schleife), eine zusätzliche Einfügeposition len+1
    in cheapest_insertion, das Zählfeld 'stops' in simulate (wird nie gelesen), clip-Untergrenze 0 gegen 1 (nur wirksam bei Punkten genau auf dem Rand), mu+1 bei der Orakel-Instanz
    (nur die Menge, nie das Verhältnis zur Kapazität), gamma 0,5 der Regel R im Orakel (bei H=0 ohne Wirkung), Regel-Standardwerte für Arbeiter und Zeitlimit.
(3) Darstellungsparameter ohne eigene Aussage: Stellenzahl beim Runden für Anzeige (round(x, 1) gegen 2 in Kennzahltabellen), Faktor 100 gegen 101 bei ganzzahlig angezeigten Prozenten
    (der Fehler liegt unter der angezeigten Stelle), Tabellenoption index=True (gleicher Inhalt mit Indexspalte), Schwelle des PDF-Seitenumbruchs (>= gegen >), lru_cache-Größe.
(4) Werkzeug-Rahmen: Kommandozeilen-Einstiegspunkte (sys.argv[1:] gegen [2:] nur ohne Argumente prüfbar), Schalter 'dont_write_bytecode', Größe in KB (1024 gegen 1025 in einer
    Ausgabezeile), Rundung (6 gegen 7 Stellen) bei einer Größe, die schon auf 1e-9 stimmt, defensive Zweige für bool/None in der Rundung.
Gefundene echte Lücken der ersten beiden Läufe sind mit Tests geschlossen (tests/test_gaps_*.py, test_gaps_round2.py); die Liste oben ist der verbleibende Rest."""

MUTANTS = [
    ('irp_routing.py', '] > Q + 1e-9:', '] > Q - 1e-9:'),
    ('irp_routing.py', ' s <= 1e-12:', ' s <= 0.0:'),
    ('irp_routing.py', ' if s <= 1e-12', ' if s < 1e-12'),
    ('irp_routing.py', 'd[ri] + load[', 'd[ri] - load['),
    ('irp_routing.py', '  d = 0 if j ', '  d = 1 if j '),
    ('irp_routing.py', '0], x[1], x[2', '0], x[2], x[2'),
    ('irp_routing.py', '    s += dist[', '    s -= dist['),
    ('irp_routing.py', 'est[i - 1]', 'est[i + 1]'),
    ('irp_routing.py', '[-1], 0]', '[-1], 1]'),
    ('irp_routing.py', ' else 0', ' else 1'),
    ('irp_routing.py', 'e(i + 1, n):', 'e(i + 2, n):'),
    ('irp_routing.py', 'nge(a + 1, le', 'nge(a - 1, le'),
    ('irp_routing.py', 'a, b] - dist[', 'a, b] + dist['),
    ('irp_routing.py', ' i == 0 else ', ' i == 1 else '),
    ('irp_routing.py', ' if j == n - 1', ' if j != n - 1'),
    ('irp_routing.py', 'e(a + 1, len(', 'e(a + 2, len('),
    ('irp_routing.py', 'ved = False', 'ved = True'),
    ('irp_routing.py', 'ute[:-1], rou', 'ute[:-2], rou'),
    ('irp_routing.py', '1][::-1]', '1][::-2]'),
    ('irp_routing.py', '1[-1] == i and r2[0] == j:', '1[-1] == i and r2[1] == j:'),
    ('irp_routing.py', 't[i - 1]', 't[i - 2]'),
    ('irp_routing.py', 'eturn 0.0', 'eturn 0.1'),
    ('irp_routing.py', ' == n - 1 els', ' == n + 1 els'),
    ('irp_routing.py', '   elif r1[0] == i and r2[-1] ', '   elif r1[0] != i and r2[-1] '),
    ('irp_routing.py', '[-1] == i and r2[-1] == j:', '[-1] == i and r2[-2] == j:'),
    ('irp_routing.py', 'e[0]] + dist[', 'e[0]] - dist['),
    ('irp_routing.py', 'nge(n - 1):', 'nge(n + 1):'),
    ('irp_routing.py', 'r1[0] == i and r2[-1] == j:', 'r1[0] == i and r2[-1] != j:'),
    ('irp_routing.py', 'v, j] + dist[', 'v, j] - dist['),
    ('irp_routing.py', 'delta < best[', 'delta <= best['),
    ('irp_routing.py', ': (-x[0], x[1', ': (-x[1], x[1'),
    ('irp_routing.py', '1[0] == i and r2[-1] ==', '1[0] == i or r2[-1] =='),
    ('irp_routing.py', '[0] - 1e-12:', '[0] - 0.0:'),
    ('irp_routing.py', ' dist[0, j] -', ' dist[1, j] -'),
    ('irp_routing.py', 'nge(i + 1, n)', 'nge(i - 1, n)'),
    ('irp_routing.py', 'r1[::-1] + r2', 'r1[::-2] + r2'),
    ('irp_routing.py', '0] == i and r2[0] == j:', '0] == i and r2[0] != j:'),
    ('irp_routing.py', 'i:j + 1][::-1', 'i:j + 2][::-1'),
    ('irp_routing.py', 'r2[::-1]', 'r2[::-2]'),
    ('irp_routing.py', '[-1] == i and r2[0] == ', '[-1] == i or r2[0] == '),
    ('irp_routing.py', '1[0] == i and r2[0] == ', '1[0] == i or r2[0] == '),
    ('irp_routing.py', 'd[rj] > Q + 1', 'd[rj] >= Q + 1'),
    ('irp_routing.py', '        elif r1[0] == i and r2[-1] ', '        elif r1[1] == i and r2[-1] '),
    ('irp_routing.py', '        elif r1[0] == i and r2[0] =', '        elif r1[1] == i and r2[0] ='),
    ('irp_routing.py', 'f pos < len(r', 'f pos <= len(r'),
    ('irp_routing.py', ' elif r1[-1] == i and', ' elif r1[-2] == i and'),
    ('irp_routing.py', ' = r2 + r1', ' = r2 - r1'),
    ('irp_routing.py', '= n - 1 else ', '= n - 2 else '),
    ('irp_routing.py', 'if ri == rj:', 'if ri != rj:'),
    ('irp_routing.py', 'f n < 3:', 'f n < 4:'),
    ('irp_routing.py', 'rev = 0', 'rev = 1'),
    ('irp_routing.py', 'route[0]] + d', 'route[1]] + d'),
    ('irp_routing.py', '  a = 0 if i ', '  a = 1 if i '),
    ('irp_routing.py', '   if r1[-1] == i and', '   if r1[-2] == i and'),
    ('irp_routing.py', 't[j + 1]', 't[j + 2]'),
    ('irp_routing.py', 'a, c] + dist[', 'a, c] - dist['),
    ('irp_routing.py', 'r1[0] == i and r2[0] == j:', 'r1[0] == i and r2[1] == j:'),
    ('irp_routing.py', 'b, d] - dist[', 'b, d] + dist['),
    ('irp_routing.py', 'st[0] - 1e-12', 'st[0] + 1e-12'),
    ('irp_routing.py', '   elif r1[0] == i and r2[0] =', '   elif r1[0] != i and r2[0] ='),
    ('irp_routing.py', '       improved = True', '       improved = False'),
    ('irp_routing.py', '1[0] == i and r2[-1] == j:', '1[0] == i and r2[-2] == j:'),
    ('irp_routing.py', 'e(n - 1):', 'e(n - 2):'),
    ('irp_routing.py', '1] == i and r2[0] == j:', '1] == i and r2[0] != j:'),
    ('irp_routing.py', 'ta < -1e-9:', 'ta < -0.0:'),
    ('irp_routing.py', ' if n < 3:', ' if n <= 3:'),
    ('irp_routing.py', '(dist[0, i] +', '(dist[1, i] +'),
    ('irp_routing.py', 'nf"), 0)', 'nf"), 1)'),
    ('irp_routing.py', 'oute[-1], 0]', 'oute[-2], 0]'),
    ('irp_routing.py', 'i:j + 1] = be', 'i:j + 2] = be'),
    ('irp_routing.py', 'est[j + 1]', 'est[j - 1]'),
    ('irp_routing.py', 't[i:j + 1] = ', 't[i:j - 1] = '),
    ('irp_routing.py', 'te) + 1):', 'te) + 2):'),
    ('irp_routing.py', 'delta < -1e-9', 'delta <= -1e-9'),
    ('irp_routing.py', ' best[0] - 1e', ' best[1] - 1e'),
    ('irp_routing.py', 'd[ri] += load[', 'd[ri] -= load['),
    ('irp_routing.py', '0, j] - dist[', '0, j] + dist['),
    ('irp_routing.py', '0, i] + dist[', '0, i] - dist['),
    ('irp_routing.py', '  elif r1[-1] == i and r2[-1] ', '  elif r1[-1] != i and r2[-1] '),
    ('irp_routing.py', '    if r1[-1] == i and r2[0] =', '    if r1[-1] != i and r2[0] ='),
    ('irp_routing.py', '1], x[2]))', '1], x[3]))'),
    ('irp_routing.py', 't[i:j + 1][::', 't[i:j - 1][::'),
    ('irp_routing.py', '> Q + 1e-9:', '> Q + 0.0:'),
    ('irp_routing.py', 'route[1:]):', 'route[2:]):'),
    ('irp_routing.py', ' = r1 + r2[::', ' = r1 - r2[::'),
    ('irp_routing.py', '1[-1] == i and r2[-1] == j:', '1[-1] == i and r2[-1] != j:'),
    ('irp_routing.py', ' if i == 0 els', ' if i != 0 els'),
    ('irp_routing.py', ' nxt] - dist[', ' nxt] + dist['),
    ('irp_routing.py', '::-1] + r2', '::-1] - r2'),
    ('irp_routing.py', '[-1] == i and r2[-1] ==', '[-1] == i or r2[-1] =='),
    ('irp_routing.py', 'oute) + 1):', 'oute) - 1):'),
    ('irp_routing.py', ' dist[0, rout', ' dist[1, rout'),
    ('irp_policy.py', ' dist[0, j] +', ' dist[1, j] +'),
    ('irp_policy.py', 'vered += q', 'vered -= q'),
    ('irp_policy.py', 'tes"] += len(p', 'tes"] -= len(p'),
    ('irp_policy.py', 'its"] += st.ge', 'its"] -= st.ge'),
    ('irp_policy.py', 'its"] += sum(l', 'its"] -= sum(l'),
    ('irp_policy.py', '] * H - 1e-12', '] * H + 1e-12'),
    ('irp_policy.py', 'ort"] += sh', 'ort"] -= sh'),
    ('irp_policy.py', 'tc[0] - 1e-12', 'tc[0] + 1e-12'),
    ('irp_policy.py', 't((cons_t - served).s', 't((cons_t + served).s'),
    ('irp_policy.py', '.C[i] - I[i],', '.C[i] + I[i],'),
    ('irp_policy.py', 'red": 0.0, "ser', 'red": 0.1, "ser'),
    ('irp_policy.py', 'red = 0.0', 'red = 0.1'),
    ('irp_policy.py', 'red": 0, "sto', 'red": 1, "sto'),
    ('irp_policy.py', 'mma * 2.0 * dis', 'mma * 2.2 * dis'),
    ('irp_policy.py', 'gamma=0.5, flee', 'gamma=0.55, flee'),
    ('irp_policy.py', '  q = min(q, in', '  q = max(q, in'),
    ('irp_policy.py', ' (1.0 + inst.', ' (1.0 - inst.'),
    ('irp_policy.py', 'red"] += st.ge', 'red"] -= st.ge'),
    ('irp_policy.py', ' None or delta', ' None and delta'),
    ('irp_policy.py', 'delta <= gamma', 'delta < gamma'),
    ('irp_policy.py', '(((cons_t - served) >', '(((cons_t + served) >'),
    ('irp_policy.py', 'st.I0[1:].sum', 'st.I0[2:].sum'),
    ('irp_policy.py', 'ing": 0.0, "sho', 'ing": 0.1, "sho'),
    ('irp_policy.py', 'sits"] += 1', 'sits"] += 2'),
    ('irp_policy.py', 'f H > 0 and r', 'f H > 1 and r'),
    ('irp_policy.py', '> Q + 1e-9:', '> Q + 0.0:'),
    ('irp_policy.py', 'ed) > 1e-9).sum(', 'ed) > 0.0).sum('),
    ('irp_policy.py', 'ing"] += dc', 'ing"] -= dc'),
    ('irp_policy.py', 'red"] += dl', 'red"] -= dl'),
    ('irp_policy.py', 'its": 0, "def', 'its": 1, "def'),
    ('irp_policy.py', 'arange(1, N + 1)', 'arange(1, N + 2)'),
    ('irp_policy.py', '] > Q + 1e-9:', '] > Q - 1e-9:'),
    ('irp_policy.py', ':pos] + [j] +', ':pos] - [j] +'),
    ('irp_policy.py', ' j] + 1e-12:', ' j] + 0.0:'),
    ('irp_policy.py', 'tes": 0, "n_v', 'tes": 1, "n_v'),
    ('irp_policy.py', ', "n_visits": 0,', ', "n_visits": 1,'),
    ('irp_policy.py', 'hr[i] + inst.', 'hr[i] - inst.'),
    ('irp_policy.py', 'st, H=0.0, gamm', 'st, H=0.1, gamm'),
    ('irp_policy.py', 'due[:-1]     ', 'due[:-2]     '),
    ('irp_policy.py', 'ops": 0}', 'ops": 1}'),
    ('irp_policy.py', '[i] = min(inst.', '[i] = max(inst.'),
    ('irp_policy.py', ') > F and due:', ') > F or due:'),
    ('irp_policy.py', 'its"] += 1', 'its"] -= 1'),
    ('irp_policy.py', 'ays": 0, "rou', 'ays": 1, "rou'),
    ('irp_policy.py', '_cost += route', '_cost -= route'),
    ('irp_policy.py', 'ays": 0, "uti', 'ays": 1, "uti'),
    ('irp_policy.py', ' I[c] += q', ' I[c] -= q'),
    ('irp_policy.py', 'oat(I[1:].sum', 'oat(I[2:].sum'),
    ('irp_policy.py', 'rred"] += 1', 'rred"] += 2'),
    ('irp_policy.py', '.C[c] - I[c])', '.C[c] + I[c])'),
    ('irp_policy.py', ' else 0', ' else 1'),
    ('irp_policy.py', 'ort": 0.0, "del', 'ort": 0.1, "del'),
    ('irp_policy.py', 'ecord=True)', 'ecord=False)'),
    ('irp_policy.py', ' and I[i] < thr[i] + ', ' and I[i] <= thr[i] + '),
    ('irp_policy.py', 'np.arange(1, N + 1)', 'np.arange(2, N + 1)'),
    ('irp_policy.py', 'ecord=False):', 'ecord=True):'),
    ('irp_policy.py', 'end"] - res["', 'end"] + res["'),
    ('irp_policy.py', '_idx] += qty[j', '_idx] -= qty[j'),
    ('irp_policy.py', 'red"] += 1', 'red"] -= 1'),
    ('irp_policy.py', 'sum"] += sum(s', 'sum"] -= sum(s'),
    ('irp_policy.py', 'rved) > 1e-9)', 'rved) >= 1e-9)'),
    ('irp_policy.py', 'its": 0}', 'its": 1}'),
    ('irp_policy.py', '_idx] + qty[j', '_idx] - qty[j'),
    ('irp_policy.py', 'ved"] += sv', 'ved"] -= sv'),
    ('irp_policy.py', 'hr[i] - 1e-12', 'hr[i] + 1e-12'),
    ('irp_policy.py', 'ort"] - tau *', 'ort"] + tau *'),
    ('irp_policy.py', ' if H > 0 and', ' if H >= 0 and'),
    ('irp_policy.py', 'ty[j] > Q + 1', 'ty[j] >= Q + 1'),
    ('irp_policy.py', 'n due and I[i] ', 'n due or I[i] '),
    ('irp_policy.py', '[i] - 1e-12]', '[i] - 0.0]'),
    ('irp_policy.py', 'ays"] += ns', 'ays"] -= ns'),
    ('irp_policy.py', 'sigma + early', 'sigma - early'),
    ('irp_policy.py', 'x if I[i] < thr[i] - ', 'x if I[i] <= thr[i] - '),
    ('irp_policy.py', '0, j] + 1e-12', '0, j] - 1e-12'),
    ('irp_policy.py', 'bestc[0] - 1e', 'bestc[1] - 1e'),
    ('irp_policy.py', 'mu * (1.0 + ins', 'mu * (1.1 + ins'),
    ('irp_policy.py', 'ved": 0.0, "n_r', 'ved": 0.1, "n_r'),
    ('irp_policy.py', 'p.arange(1, N + 1)', 'p.arange(1, N - 1)'),
    ('irp_policy.py', 'red": 0, "opt', 'red": 1, "opt'),
    ('irp_policy.py', 'early=0.0, reco', 'early=0.1, reco'),
    ('irp_policy.py', ', N + 1):', ', N + 2):'),
    ('irp_policy.py', 'H > 0 and route', 'H > 0 or route'),
    ('irp_policy.py', 'ing"] + p * r', 'ing"] - p * r'),
    ('irp_policy.py', 'its", 0)', 'its", 1)'),
    ('irp_policy.py', ' in range(1, N + 1):', ' in range(2, N + 1):'),
    ('irp_policy.py', 'early=0.0):', 'early=0.1):'),
    ('irp_policy.py', 'delta < bestc', 'delta <= bestc'),
    ('irp_policy.py', 'utes) > F and', 'utes) >= F and'),
    ('irp_policy.py', ' I, H=0.0, gamm', ' I, H=0.1, gamm'),
    ('irp_policy.py', 'gamma=0.5, plan', 'gamma=0.55, plan'),
    ('irp_policy.py', '+ [j] + route', '+ [j] - route'),
    ('irp_policy.py', 'ost = 0.0', 'ost = 0.1'),
    ('irp_policy.py', 'red", 0)', 'red", 1)'),
    ('irp_policy.py', 'ays"] += 1 if ', 'ays"] -= 1 if '),
    ('irp_policy.py', '[0] - 1e-12:', '[0] - 0.0:'),
    ('irp_policy.py', 'I = I - serve', 'I = I + serve'),
    ('irp_policy.py', '* H - 1e-12]', '* H - 0.0]'),
    ('irp_policy.py', '"] += 1 if pl', '"] += 2 if pl'),
    ('irp_policy.py', 'sum": 0.0,', 'sum": 0.1,'),
    ('irp_policy.py', '(1, N + 1):', '(1, N - 1):'),
    ('irp_model.py', ']) ** 2).sum(', ']) ** 3).sum('),
    ('irp_model.py', 'ormal(0, 0.07', 'ormal(1, 0.07'),
    ('irp_model.py', '0, size, size=(N, 2))', '0, size, size=(N, 3))'),
    ('irp_model.py', ', (D, 1))', ', (D, 2))'),
    ('irp_model.py', 'nk_hi=14.0, kapp', 'nk_hi=15.4, kapp'),
    ('irp_model.py', 'sigma > 0:', 'sigma >= 0:'),
    ('irp_model.py', '[lab] + rng.n', '[lab] - rng.n'),
    ('irp_model.py', 'ate([[0.0], mu ', 'ate([[0.1], mu '),
    ('irp_model.py', 'mu_lo=6.0, mu_h', 'mu_lo=6.6, mu_h'),
    ('irp_model.py', '.sum(-1))', '.sum(-2))'),
    ('irp_model.py', '(pts, 0, size', '(pts, 1, size'),
    ('irp_model.py', '0.25, 1.0, size', '0.25, 1.1, size'),
    ('irp_model.py', '/ 2, -0.5 * siz', '/ 2, -0.55 * siz'),
    ('irp_model.py', 'nk_lo=8.0, tank', 'nk_lo=8.8, tank'),
    ('irp_model.py', 'gma > 0:', 'gma > 1:'),
    ('irp_model.py', ' pfac=0.05, D=90', ' pfac=0.055, D=90'),
    ('irp_model.py', ' size=100.0, sigm', ' size=110.0, sigm'),
    ('irp_model.py', 'eed * 7919 + 13)', 'eed * 7920 + 13)'),
    ('irp_model.py', 'mu_hi=14.0, tank', 'mu_hi=15.4, tank'),
    ('irp_model.py', 'e=(k, 2))', 'e=(k, 3))'),
    ('irp_model.py', 'ed, N=20, size', 'ed, N=21, size'),
    ('irp_model.py', 'ns[:, 0] = 0.', 'ns[:, 1] = 0.'),
    ('irp_model.py', '919 + 13)', '919 + 14)'),
    ('irp_model.py', 'iform(0.25, 1.0,', 'iform(0.275, 1.0,'),
    ('irp_model.py', '.3, Q=300.0, F=6,', '.3, Q=330.0, F=6,'),
    ('irp_model.py', '(0.0, 0.0), "fa', '(0.0, 0.1), "fa'),
    ('irp_model.py', 'sigma=0.3, Q=30', 'sigma=0.33, Q=30'),
    ('irp_model.py', 'ize / 2, size', 'ize / 3, size'),
    ('irp_model.py', 'egers(0, k, s', 'egers(1, k, s'),
    ('irp_model.py', 'ape = 1.0 / (si', 'ape = 1.1 / (si'),
    ('irp_model.py', 'tered=False, mu_l', 'tered=True, mu_l'),
    ('irp_model.py', '  k = 4', '  k = 5'),
    ('irp_model.py', 'kappa=1.0, roun', 'kappa=1.1, roun'),
    ('irp_model.py', 'ize / 2, -0.5', 'ize / 3, -0.5'),
    ('irp_model.py', ' 7919 + 13)', ' 7919 - 13)'),
    ('irp_model.py', ' 0] = 0.0', ' 0] = 0.1'),
    ('irp_model.py', 'iform(0, size', 'iform(1, size'),
    ('irp_model.py', 'e, :] - xy[No', 'e, :] + xy[No'),
    ('irp_model.py', 'nst.C[1:] * r', 'nst.C[2:] * r'),
    ('irp_model.py', '05, D=90, depo', '05, D=91, depo'),
    ('irp_model.py', ', N + 1)) * i', ', N + 2)) * i'),
    ('irp_model.py', ' * size, size=(N, 2))', ' * size, size=(N, 3))'),
    ('irp_model.py', 'al(0, 0.07 * siz', 'al(0, 0.077 * siz'),
    ('irp_model.py', '(D, N + 1)) *', '(D, N - 1)) *'),
    ('irp_model.py', 'size, 0.85 * siz', 'size, 0.935 * siz'),
    ('irp_model.py', 'er": (0.0, 0.0)', 'er": (0.1, 0.0)'),
    ('irp_model.py', '.0, F=6, pfac', '.0, F=7, pfac'),
    ('irp_model.py', 'iform(0.15 * siz', 'iform(0.165 * siz'),
    ('irp_model.py', 'ate([[0.0], ins', 'ate([[0.1], ins'),
    ('irp_model.py', 'ate([[0.0], mu]', 'ate([[0.1], mu]'),
    ('irp_model.py', 'ize / 2), "co', 'ize / 3), "co'),
    ('irp_oracle.py', 'I[D - 1, i] f', 'I[D - 2, i] f'),
    ('irp_oracle.py', 'rkers=8):', 'rkers=9):'),
    ('irp_oracle.py', '=Q, F=1, roun', '=Q, F=2, roun'),
    ('irp_oracle.py', 'YS, Q=150.0):', 'YS, Q=165.0):'),
    ('irp_oracle.py', 'c.get(0)', 'c.get(1)'),
    ('irp_oracle.py', ' in range(1, N + 1)) ', ' in range(2, N + 1)) '),
    ('irp_oracle.py', 'OMERS or n_day', 'OMERS and n_day'),
    ('irp_oracle.py', '(prev + q[t, ', '(prev - q[t, '),
    ('irp_oracle.py', 'ecord=True)', 'ecord=False)'),
    ('irp_oracle.py', '(1, N + 1)) <', '(1, N - 1)) <'),
    ('irp_oracle.py', 'nk_lo=3.0, tank', 'nk_lo=3.3, tank'),
    ('irp_oracle.py', ', N + 1)) <= ', ', N + 2)) <= '),
    ('irp_oracle.py', '"R": (0.0, 0.5,', '"R": (0.1, 0.5,'),
    ('irp_oracle.py', ' 0.5, 0.0), "P"', ' 0.5, 0.1), "P"'),
    ('irp_oracle.py', 'n max(0.0, cool', 'n max(0.1, cool'),
    ('irp_oracle.py', '"E": (0.0, 0.5,', '"E": (0.1, 0.5,'),
    ('irp_oracle.py', '.mu + 1)', '.mu + 2)'),
    ('irp_oracle.py', 'i] == 0).Only', 'i] == 1).Only'),
    ('irp_oracle.py', '(skip[0], ski', '(skip[1], ski'),
    ('irp_oracle.py', 'limit=60.0, work', 'limit=66.0, work'),
    ('irp_oracle.py', 'e(N + 1)]', 'e(N + 2)]'),
    ('irp_oracle.py', 'limit=20.0, work', 'limit=22.0, work'),
    ('irp_oracle.py', 'ime() - t0', 'ime() + t0'),
    ('irp_oracle.py', ' 1, i] for i in range(1, N + 1))', ' 1, i] for i in range(2, N + 1))'),
    ('irp_oracle.py', ' if i == j:', ' if i != j:'),
    ('irp_oracle.py', 'sigma=0.0, Q=Q,', 'sigma=0.1, Q=Q,'),
    ('irp_oracle.py', 'gap": 100.0 * (j ', 'gap": 110.0 * (j '),
    ('irp_oracle.py', '+ 1)) <= Q)', '+ 1)) < Q)'),
    ('irp_oracle.py', 'ns[:, 0] = 0.', 'ns[:, 1] = 0.'),
    ('irp_oracle.py', 'ur != 0:', 'ur != 1:'),
    ('irp_oracle.py', 'd cur != 0:', 'd cur == 0:'),
    ('irp_oracle.py', ' != j and solve', ' != j or solve'),
    ('irp_oracle.py', ' prev + q[t, ', ' prev - q[t, '),
    ('irp_oracle.py', '_days > MAX_D', '_days >= MAX_D'),
    ('irp_oracle.py', ' 0] = 0.0', ' 0] = 0.1'),
    ('irp_oracle.py', 'st.mu + 1)', 'st.mu - 1)'),
    ('irp_oracle.py', 'omers > MAX_C', 'omers >= MAX_C'),
    ('irp_oracle.py', '- 1, i] for i in range(1, N + 1))', '- 1, i] for i in range(1, N + 2))'),
    ('irp_oracle.py', ' * (j - j_opt', ' * (j + j_opt'),
    ('irp_oracle.py', 't, i] <= int(i', 't, i] < int(i'),
    ('irp_oracle.py', 'ldown - (now ', 'ldown + (now '),
    ('irp_oracle.py', '(obj) - tau_i', '(obj) + tau_i'),
    ('irp_oracle.py', 'TAU = 0.6      ', 'TAU = 0.66      '),
    ('irp_oracle.py', ' = 7, 6  # di', ' = 7, 7  # di'),
    ('irp_oracle.py', 'eturn 0.0', 'eturn 0.1'),
    ('irp_oracle.py', 'm(I[D - 1, i]', 'm(I[D + 1, i]'),
    ('irp_oracle.py', ' (now - last)', ' (now + last)'),
    ('irp_oracle.py', '(0.0, 0.5, floa', '(0.0, 0.55, floa'),
    ('irp_oracle.py', 'AYS = 7, 6  #', 'AYS = 8, 6  #'),
    ('irp_oracle.py', 'mma), 0.0), "E"', 'mma), 0.1), "E"'),
    ('irp_results.py', ' best - 3.0)}', ' best + 3.0)}'),
    ('irp_results.py', ' if v >= best ', ' if v > best '),
    ('irp_results.py', ' if v > 0), "', ' if v >= 0), "'),
    ('irp_results.py', 'f v < 0),', 'f v < 1),'),
    ('irp_results.py', "['F'] > 1 els", "['F'] >= 1 els"),
    ('irp_results.py', 'iw[p] - ic[p]', 'iw[p] + ic[p]'),
    ('irp_results.py', 'else -1', 'else -2'),
    ('irp_results.py', ', se) == "pos"', ', se) != "pos"'),
    ('irp_results.py', 'xsize=4)', 'xsize=5)'),
    ('irp_results.py', 'aried[0]) if ', 'aried[1]) if '),
    ('irp_results.py', "F'] > 1 else ", "F'] > 2 else "),
    ('irp_results.py', ' if f > 1 els', ' if f >= 1 els'),
    ('irp_results.py', '), 0) + 1', '), 0) - 1'),
    ('irp_results.py', 'f l > 1 else ', 'f l > 2 else '),
    ('irp_results.py', 'r key < best[', 'r key <= best['),
    ('irp_results.py', ' None or key <', ' None and key <'),
    ('irp_results.py', '"_g")[1]) <= ', '"_g")[2]) <= '),
    ('irp_results.py', '["F"] != base[', '["F"] == base['),
    ('irp_results.py', 'n)) > 1e-9):', 'n)) > 0.0):'),
    ('irp_results.py', 'if any(cfg[k] != C.BASE_CFG[k]', 'if any(cfg[k] == C.BASE_CFG[k]'),
    ('irp_results.py', 'ia[p] != ib[p]', 'ia[p] == ib[p]'),
    ('irp_results.py', 'ean"] < 0]', 'ean"] <= 0]'),
    ('irp_results.py', ' mean >= C.WIN', ' mean > C.WIN'),
    ('irp_results.py', "lo'], 0)} bis", "lo'], 1)} bis"),
    ('irp_results.py', ' 0) + 1', ' 0) + 2'),
    ('irp_results.py', ' t: t[2])', ' t: t[3])'),
    ('irp_results.py', 'ppa"] != base[', 'ppa"] == base['),
    ('irp_results.py', '["N"] != base[', '["N"] == base['),
    ('irp_results.py', 'f v > 0), "ne', 'f v > 1), "ne'),
    ('irp_results.py', ', se) == "neg"', ', se) != "neg"'),
    ('irp_results.py', 'or any(cfg[k] != C.BASE_CFG[k]', 'or any(cfg[k] == C.BASE_CFG[k]'),
    ('irp_results.py', '(path or DATA_', '(path and DATA_'),
    ('irp_results.py', 'ame"] == name]', 'ame"] != name]'),
    ('irp_results.py', 'fg[k] != base[', 'fg[k] == base['),
    ('irp_results.py', '"_H")[1].spli', '"_H")[2].spli'),
    ('irp_results.py', ' 0.0, 0.0))', ' 0.0, 0.1))'),
    ('irp_results.py', '      or int(p', '      and int(p'),
    ('irp_results.py', ' if l > 1 els', ' if l >= 1 els'),
    ('irp_results.py', 'max": max(r["ti', 'max": min(r["ti'),
    ('irp_results.py', ' else -1', ' else +1'),
    ('irp_results.py', 'et(0, 0), "by', 'et(0, 1), "by'),
    ('irp_results.py', 'et(k) == v for', 'et(k) != v for'),
    ('irp_results.py', 'ositive": sum(1 for v in mean', 'ositive": sum(2 for v in mean'),
    ('irp_results.py', 'TIONS or s not', 'TIONS and s not'),
    ('irp_results.py', 'igits=1):', 'igits=2):'),
    ('irp_results.py', 'iff), 0) + 1', 'iff), 1) + 1'),
    ('irp_results.py', 'N_PCT and verdi', 'N_PCT or verdi'),
    ('irp_results.py', 'TIONS or f not', 'TIONS and f not'),
    ('irp_results.py', "hi'], 0)} Tag", "hi'], 1)} Tag"),
    ('irp_results.py', 'hers) or any(c', 'hers) and any(c'),
    ('irp_results.py', 'est - 3.0)}', 'est - 3.3)}'),
    ('irp_results.py', '("_")[0]), fl', '("_")[1]), fl'),
    ('irp_results.py', 'key": max(means', 'key": min(means'),
    ('irp_results.py', 'f f > 1 else ', 'f f > 2 else '),
    ('irp_results.py', ')[1]) <= 0.25)', ')[1]) < 0.25)'),
    ('irp_results.py', 't.get(0, 0), ', 't.get(1, 0), '),
    ('irp_results.py', 'pa\'], 0)}")', 'pa\'], 1)}")'),
    ('irp_results.py', '0")), sum(1 for _, k,', '0")), sum(2 for _, k,'),
    ('irp_results.py', 'est": sum(1 for v in ', 'est": sum(2 for v in '),
    ('irp_results.py', ' mean > facto', ' mean >= facto'),
    ('irp_results.py', 's(pen - int(p', 's(pen + int(p'),
    ('irp_results.py', 'n"] < 0]', 'n"] < 1]'),
    ('irp_results.py', 'TIONS or abs(p', 'TIONS and abs(p'),
    ('irp_results.py', ' best[0]:', ' best[1]:'),
    ('irp_results.py', '["Q"] != base[', '["Q"] == base['),
    ('irp_results.py', 'hi"]) != (base', 'hi"]) == (base'),
    ('irp_results.py', 'ug)", 0.0, 0.0)', 'ug)", 0.1, 0.0)'),
    ('irp_results.py', 'egative": sum(1 for v in mean', 'egative": sum(2 for v in mean'),
    ('irp_results.py', 'est = max(means', 'est = min(means'),
    ('irp_results.py', ' if v < 0),', ' if v <= 0),'),
    ('irp_results.py', ']) <= 0.25)', ']) <= 0.275)'),
    ('irp_results.py', 'otal, sum(1 for _, k,', 'otal, sum(2 for _, k,'),
    ('irp_results.py', 'pen)) > 1e-9)', 'pen)) >= 1e-9)'),
    ('irp_results.py', 'TIONS or q not', 'TIONS and q not'),
    ('irp_results.py', 'gma"] != base[', 'gma"] == base['),
    ('irp_results.py', ' mean < -fact', ' mean <= -fact'),
    ('irp_results.py', 'pot"] != base[', 'pot"] == base['),
    ('irp_results.py', 'fac"] != base[', 'fac"] == base['),
    ('irp_results.py', 'y.split("_g")[1])', 'y.split("_g")[2])'),
    ('irp_stories.py', ' [(gp < 0, f"', ' [(gp <= 0, f"'),
    ('irp_stories.py', 'AIN = 10.0', 'AIN = 11.0'),
    ('irp_stories.py', 'US_H, 1.0), R.p', 'US_H, 1.1), R.p'),
    ('irp_stories.py', 'e"], -1), f"f', 'e"], -2), f"f'),
    ('irp_stories.py', ': {_de(gp, 1, True)} %"), (ge < ', ': {_de(gp, 1, False)} %"), (ge < '),
    ('irp_stories.py', 'ean"] >= BIG_M', 'ean"] > BIG_M'),
    ('irp_stories.py', 'mean, 1, True', 'mean, 2, True'),
    ('irp_stories.py', "_P'], 0)} Ein", "_P'], 1)} Ein"),
    ('irp_stories.py', '(gp < 0, f"Bü', '(gp < 1, f"Bü'),
    ('irp_stories.py', '], 1, True)} %")', '], 1, False)} %")'),
    ('irp_stories.py', ' sign=False):', ' sign=True):'),
    ('irp_stories.py', 'IN = -10.0', 'IN = -11.0'),
    ('irp_stories.py', 'se"]) and g["me', 'se"]) or g["me'),
    ('irp_stories.py', '(ga > 0, f"mi', '(ga > 1, f"mi'),
    ('irp_stories.py', 'reaktiv: {_de(gp, 1, True)} %"), (ga ', 'reaktiv: {_de(gp, 2, True)} %"), (ga '),
    ('irp_stories.py', 's(gp) < DAY_F', 's(gp) <= DAY_F'),
    ('irp_stories.py', 'AIN = 2.0', 'AIN = 2.2'),
    ('irp_stories.py', 'igits=1, sign', 'igits=2, sign'),
    ('irp_stories.py', 'LEET_MIN_GAIN and _clear(g["mea', 'LEET_MIN_GAIN or _clear(g["mea'),
    ('irp_stories.py', 'a, 1, True)} %")', 'a, 1, False)} %")'),
    ('irp_stories.py', " {_de(100 * g['", " {_de(101 * g['"),
    ('irp_stories.py', 'sign=+1):', 'sign=+2):'),
    ('irp_stories.py', ', (ge < 0, f"', ', (ge <= 0, f"'),
    ('irp_stories.py', 'AIN = 25.0', 'AIN = 27.5'),
    ('irp_stories.py', 'ean"] >= FLEET', 'ean"] > FLEET'),
    ('irp_stories.py', 'ean"] - b["me', 'ean"] + b["me'),
    ('irp_stories.py', '  (sp < sr, f', '  (sp <= sr, f'),
    ('irp_stories.py', ' [(gp >= DAY_F', ' [(gp > DAY_F'),
    ('irp_stories.py', ' BIG_MIN_GAIN and _clear(g["mea', ' BIG_MIN_GAIN or _clear(g["mea'),
    ('irp_stories.py', ' [(gp >= DAY_B', ' [(gp > DAY_B'),
    ('irp_stories.py', 'e(ga, 1, True', 'e(ga, 2, True'),
    ('irp_stories.py', '_MAX_GAIN and _clear(g[', '_MAX_GAIN or _clear(g['),
    ('irp_stories.py', 't_P"] < cell[', 't_P"] <= cell['),
    ('irp_stories.py', 'ta, Q=100.0)', 'ta, Q=110.0)'),
    ('irp_stories.py', ' [(gp > 0, f"', ' [(gp >= 0, f"'),
    ('irp_stories.py', '5 %: {_de(gp, 1, True)} %")]', '5 %: {_de(gp, 2, True)} %")]'),
    ('irp_stories.py', 'ta, Q=600.0), R.f', 'ta, Q=660.0), R.f'),
    ('irp_stories.py', '5 %: {_de(gp, 1, True)} %"),', '5 %: {_de(gp, 2, True)} %"),'),
    ('irp_stories.py', 'n, 1, True)} ± {', 'n, 1, False)} ± {'),
    ('irp_stories.py', ': {_de(gp, 1, True)} %"), (ga > ', ': {_de(gp, 1, False)} %"), (ga > '),
    ('irp_stories.py', 'ARE = 0.0', 'ARE = 0.1'),
    ('irp_stories.py', 'e"], -1), f"G', 'e"], -2), f"G'),
    ('irp_stories.py', ' sign > 0 els', ' sign >= 0 els'),
    ('irp_stories.py', 'AIN = 15.0      ', 'AIN = 16.5      '),
    ('irp_stories.py', 'AIN = 5.0      ', 'AIN = 5.5      '),
    ('irp_stories.py', 'S_H = 12', 'S_H = 13'),
    ('irp_stories.py', 'an"]) < FULL_', 'an"]) <= FULL_'),
    ('irp_stories.py', "['mean'], 1, True)} g", "['mean'], 2, True)} g"),
    ('irp_stories.py', 'ean"] > margi', 'ean"] >= margi'),
    ('irp_stories.py', '_OK = 0.25', '_OK = 0.275'),
    ('irp_stories.py', 'ean"] >= STAND', 'ean"] > STAND'),
    ('irp_stories.py', 'oss"] <= STAND', 'oss"] < STAND'),
    ('irp_stories.py', ' 5 %: {_de(gp, 1, True)} %"),', ' 5 %: {_de(gp, 1, False)} %"),'),
    ('irp_stories.py', '(gp > 0, f"Bü', '(gp > 1, f"Bü'),
    ('irp_stories.py', 'ta, F=1)', 'ta, F=2)'),
    ('irp_stories.py', 'ign > 0 else ', 'ign > 1 else '),
    ('irp_stories.py', 'ta, Q=150.0)', 'ta, Q=165.0)'),
    ('irp_stories.py', '15 %: {_de(gp, 1, True)} %")]', '15 %: {_de(gp, 1, False)} %")]'),
    ('irp_stories.py', 'ean"] < GENER', 'ean"] <= GENER'),
    ('irp_stories.py', ' 3 %: {_de(gp, 1, True)} %")]', ' 3 %: {_de(gp, 1, False)} %")]'),
    ('irp_presets.py', 'd"] = True', 'd"] = False'),
    ('irp_presets.py', 'c.lo, min(spec.', 'c.lo, max(spec.'),
    ('irp_presets.py', 'round(max(spec.', 'round(min(spec.'),
    ('irp_presets.py', 'eturn min(spec.', 'eturn max(spec.'),
    ('irp_presets.py', 'abs(o - value', 'abs(o + value'),
    ('irp_presets.py', 'rozen=True)', 'rozen=False)'),
    ('irp_constants.py', 'D_N = 200      ', 'D_N = 201      '),
    ('irp_constants.py', 'AYS = 120      ', 'AYS = 121      '),
    ('irp_constants.py', ' = 3, 0.5      ', ' = 3, 0.55      '),
    ('irp_constants.py', ' 0.6, 1.0), 0.3', ' 0.6, 1.1), 0.3'),
    ('irp_constants.py', '=300, fleet=6, sigma=0.3, penalty=5, horizon=3, gamma=0.5, early=2, s', '=300, fleet=6, sigma=0.3, penalty=6, horizon=3, gamma=0.5, early=2, s'),
    ('irp_constants.py', '.0, early=2, seed=SEE', '.0, early=3, seed=SEE'),
    ('irp_constants.py', '6, 8, 12), 3  ', '6, 8, 13), 3  '),
    ('irp_constants.py', 'y=600, fleet=6, sigma=0.3, penalty=5, horizon=3', 'y=600, fleet=6, sigma=0.33, penalty=5, horizon=3'),
    ('irp_constants.py', 'LT = (0.1, 0.25', 'LT = (0.11, 0.25'),
    ('irp_constants.py', 'LT = (100, 150,', 'LT = (101, 150,'),
    ('irp_constants.py', '0.01, 5: 0.05', '0.01, 6: 0.05'),
    ('irp_constants.py', 'y=600, fleet=6, sigma=0.3, penalty=5, horizon=3, gamma=0.5, early=2, seed=SEED_DEFAULT),', 'y=600, fleet=6, sigma=0.3, penalty=5, horizon=3, gamma=0.5, early=3, seed=SEED_DEFAULT),'),
    ('irp_constants.py', 'y=600, fleet=6, sigma=0.3, penalty=5, horizon=3, gamma=0.5, early=2, seed=SEED_DEFAULT),', 'y=600, fleet=6, sigma=0.3, penalty=5, horizon=4, gamma=0.5, early=2, seed=SEED_DEFAULT),'),
    ('irp_constants.py', ' capacity=300, fleet=1,', ' capacity=301, fleet=1,'),
    ('irp_constants.py', '0.05, 25: 0.25', '0.05, 26: 0.25'),
    ('irp_constants.py', ' "Q": 300.0, "F":', ' "Q": 330.0, "F":'),
    ('irp_constants.py', 'LT = (0, 299)', 'LT = (1, 299)'),
    ('irp_constants.py', '1.0), 0.3', '1.0), 0.33'),
    ('irp_constants.py', 'AC = {1: 0.01', 'AC = {2: 0.01'),
    ('irp_constants.py', '=100, fleet=6, sigma=0.3, penalty=5, horizon=3, gamma=0.5, early=2, s', '=100, fleet=6, sigma=0.3, penalty=6, horizon=3, gamma=0.5, early=2, s'),
    ('irp_constants.py', 'ict(customers=20, capacity=100', 'ict(customers=21, capacity=100'),
    ('irp_constants.py', '= (1, 5, 25, ', '= (1, 6, 25, '),
    ('irp_constants.py', '50, fleet=6, sigma=0.', '50, fleet=7, sigma=0.'),
    ('irp_constants.py', 'GHT = 380', 'GHT = 381'),
    ('irp_constants.py', ', 3), 2      ', ', 3), 3      '),
    ('irp_constants.py', ', 6), 6', ', 6), 7'),
    ('irp_constants.py', '=1, sigma=0.3, penalty=', '=1, sigma=0.33, penalty='),
    ('irp_constants.py', '0.25, 100: 1.0}', '0.25, 101: 1.0}'),
    ('irp_constants.py', 'ppa": 1.0, "dep', 'ppa": 1.1, "dep'),
    ('irp_constants.py', ' 450, 600, 1000', ' 450, 601, 1000'),
    ('irp_constants.py', 'MMA = 3, 0.5 ', 'MMA = 4, 0.5 '),
    ('irp_constants.py', '=100, fleet=6, sigma=0.3, penalty=5, horizon=3, gamma=0.5, early=2, seed=SEED_DEFAULT),', '=100, fleet=6, sigma=0.3, penalty=5, horizon=3, gamma=0.55, early=2, seed=SEED_DEFAULT),'),
    ('irp_constants.py', 'ty=300, fleet=6, sigma=0.3, p', 'ty=300, fleet=7, sigma=0.3, p'),
    ('irp_constants.py', '299), 211', '299), 212'),
    ('irp_constants.py', '= (0, 299), 211', '= (0, 300), 211'),
    ('irp_constants.py', 'y=150, fleet=6, sigma=0.3, penalty=5, horizon=1', 'y=150, fleet=6, sigma=0.33, penalty=5, horizon=1'),
    ('irp_constants.py', 'ict(customers=20, capacity=600', 'ict(customers=21, capacity=600'),
    ('irp_constants.py', ' capacity=300, fleet=6,', ' capacity=301, fleet=6,'),
    ('irp_constants.py', '1, 2, 6), 6', '1, 2, 7), 6'),
    ('irp_constants.py', '=1, sigma=0.3, penalty=5, horizon=3, gamma=0.5, early=2, seed=SEED_DEFAULT),', '=1, sigma=0.3, penalty=5, horizon=3, gamma=0.5, early=3, seed=SEED_DEFAULT),'),
    ('irp_format.py', '1)) < 1e-9 else ', '1)) < 0.0 else '),
    ('irp_format.py', 'abs(v - round', 'abs(v + round'),
    ('irp_format.py', 'int(v, signed=False):', 'int(v, signed=True):'),
    ('irp_format.py', 'num(v, digits=1, signed=False', 'num(v, digits=2, signed=False'),
    ('irp_format.py', 'igned=True):', 'igned=False):'),
    ('irp_format.py', 'se f"{100.0 * v:.', 'se f"{110.0 * v:.'),
    ('irp_format.py', 'e, digits=1, signed=T', 'e, digits=2, signed=T'),
    ('irp_format.py', ', 1)) < 1e-9 ', ', 1)) <= 1e-9 '),
    ('irp_format.py', 'm(v, digits=1, signed=False):', 'm(v, digits=1, signed=True):'),
    ('irp_format.py', 'ost(v, signed=False):', 'ost(v, signed=True):'),
    ('irp_format.py', 'nd(v, 1)) < 1', 'nd(v, 2)) < 1'),
    ('irp_live.py', ' 0.5, 0.0), "P"', ' 0.5, 0.1), "P"'),
    ('irp_live.py', 'ys"], 1:] / l', 'ys"], 2:] / l'),
    ('irp_live.py', '"E": (0.0, 0.5,', '"E": (0.1, 0.5,'),
    ('irp_live.py', '"P", I[c], c) == "Mitnahme" fo', '"P", I[c], c) != "Mitnahme" fo'),
    ('irp_live.py', ' "E" else 0.0', ' "E" else 0.1'),
    ('irp_live.py', 'xy[a] - xy[b]', 'xy[a] + xy[b]'),
    ('irp_live.py', 's[t])[0]', 's[t])[1]'),
    ('irp_live.py', ' j_r > 0 else 0.0', ' j_r > 0 else 0.1'),
    ('irp_live.py', 'ind"] == "Mitn', 'ind"] != "Mitn'),
    ('irp_live.py', '["C"][1:]).me', '["C"][2:]).me'),
    ('irp_live.py', ': t + 1}', ': t + 2}'),
    ('irp_live.py', '"R": (0.0, 0.5,', '"R": (0.1, 0.5,'),
    ('irp_live.py', 'g": t + 1}', 'g": t - 1}'),
    ('irp_live.py', 'plan, 1):', 'plan, 2):'),
    ('irp_live.py', 'ecord=True)', 'ecord=False)'),
    ('irp_live.py', '= sum(1 for r', '= sum(2 for r'),
    ('irp_live.py', 'd"] > 0 else ', 'd"] > 1 else '),
    ('irp_live.py', 'mers) + [0]', 'mers) - [0]'),
    ('irp_live.py', 'ts = [0] + li', 'ts = [1] + li'),
    ('irp_live.py', '[i] - 1e-12 else ', '[i] - 0.0 else '),
    ('irp_live.py', 'days) >= limit', 'days) > limit'),
    ('irp_live.py', '"P", I[c], c) == "Mitnahme")', '"P", I[c], c) != "Mitnahme")'),
    ('irp_live.py', '(0.0, 0.5, floa', '(0.0, 0.55, floa'),
    ('irp_live.py', ', pts[1:])))', ', pts[2:])))'),
    ('irp_live.py', 'j_r > 0 else ', 'j_r > 1 else '),
    ('irp_live.py', 'ed"] > 0 else 0.0', 'ed"] > 0 else 0.1'),
    ('irp_live.py', 'pts[:-1], pts', 'pts[:-2], pts'),
    ('irp_live.py', ': sum(1 for x', ': sum(2 for x'),
    ('irp_live.py', 'limit=8):', 'limit=9):'),
    ('irp_live.py', 's) + [0]', 's) + [1]'),
    ('irp_live.py', '(day) - 1', '(day) + 1'),
    ('irp_live.py', 'eff = min(q, li', 'eff = max(q, li'),
    ('irp_live.py', 'mma), 0.0), "E"', 'mma), 0.1), "E"'),
    ('irp_live.py', ' (j_r - rule[', ' (j_r + rule['),
    ('irp_live.py', '(0.0, 0.5, 0.0)', '(0.0, 0.55, 0.0)'),
    ('irp_live.py', 'n"] = 100.0 * (j_', 'n"] = 110.0 * (j_'),
    ('irp_live.py', 'gma"] + early', 'gma"] - early'),
    ('irp_live.py', '"][c] - I[c])', '"][c] + I[c])'),
    ('irp_live.py', 'end(t + 1)', 'end(t - 1)'),
    ('irp_live.py', 'f I_i < thres', 'f I_i <= thres'),
    ('irp_live.py', 'd(t + 1)', 'd(t + 2)'),
    ('irp_live.py', 'f j_r > 0 els', 'f j_r >= 0 els'),
    ('irp_live.py', 'y)[i] - 1e-12', 'y)[i] + 1e-12'),
    ('irp_live.py', 'ay) - 1', 'ay) - 2'),
    ('irp_live.py', 'eturn 0.0', 'eturn 0.1'),
    ('irp_live.py', '"] * (1.0 + liv', '"] * (1.1 + liv'),
    ('irp_live.py', '= [0] + list(', '= [0] - list('),
    ('irp_live.py', ' rule == "E" e', ' rule != "E" e'),
    ('irp_live.py', 'red"] > 0 els', 'red"] >= 0 els'),
    ('irp_live.py', 'early=0.0):', 'early=0.1):'),
    ('irp_ui_panel.py', 'il"], 2), "Fe', 'il"], 3), "Fe'),
    ('irp_ui_panel.py', '], 1, True)} ± {', '], 1, False)} ± {'),
    ('irp_ui_panel.py', '= 0.0 and mean ', '= 0.0 or mean '),
    ('irp_ui_panel.py', "m(g['q1'], 1, True)}; {F.fmt_num", "m(g['q1'], 1, False)}; {F.fmt_num"),
    ('irp_ui_panel.py', 'mean, 1, True', 'mean, 2, True'),
    ('irp_ui_panel.py', "pm['median'], 1, True)} [{F.f", "pm['median'], 2, True)} [{F.f"),
    ('irp_ui_panel.py', 'lumns(2)', 'lumns(3)'),
    ('irp_ui_panel.py', '], 1, True)} %."', '], 1, False)} %."'),
    ('irp_ui_panel.py', 'rt"], 0)})', 'rt"], 1)})'),
    ('irp_ui_panel.py', 'se == 0.0 and m', 'se == 0.1 and m'),
    ('irp_ui_panel.py', "['mean'], 1, True)} %", "['mean'], 2, True)} %"),
    ('irp_ui_panel.py', '.50"] - jo) /', '.50"] + jo) /'),
    ('irp_ui_panel.py', "'P']['diff'], True)} ({F.fmt_num", "'P']['diff'], False)} ({F.fmt_num"),
    ('irp_ui_panel.py', '\'E\'][\'gain\'], 1, True)} %)", ', '\'E\'][\'gain\'], 2, True)} %)", '),
    ('irp_ui_panel.py', "P']['short'], 0)} / {F.fmt_nu", "P']['short'], 1)} / {F.fmt_nu"),
    ('irp_ui_panel.py', 'index=True)', 'index=False)'),
    ('irp_ui_panel.py', '\'P\'][\'gain\'], 1, True)} %)", ', '\'P\'][\'gain\'], 2, True)} %)", '),
    ('irp_ui_panel.py', '"P"]["gain"], 1, True), F.fmt', '"P"]["gain"], 2, True), F.fmt'),
    ('irp_ui_panel.py', "_R'], 0)} → {", "_R'], 1)} → {"),
    ('irp_ui_panel.py', "'R']['util'], 2)} / {F.fmt_nu", "'R']['util'], 3)} / {F.fmt_nu"),
    ('irp_ui_panel.py', '[\'P\'][\'gain\'], 1, True)} %)", delta_colo', '[\'P\'][\'gain\'], 1, False)} %)", delta_colo'),
    ('irp_ui_panel.py', '], 1, True)}]",', '], 1, False)}]",'),
    ('irp_ui_panel.py', "['mean'], 1, True)} ±", "['mean'], 2, True)} ±"),
    ('irp_ui_panel.py', 'um(v, 2) for ', 'um(v, 3) for '),
    ('irp_ui_panel.py', 'ch"], 1), "Li', 'ch"], 2), "Li'),
    ('irp_ui_panel.py', 'an == 0.0) else', 'an == 0.1) else'),
    ('irp_ui_panel.py', 'v_gain"], 1, True),', 'v_gain"], 2, True),'),
    ('irp_ui_panel.py', '(r[\'q3\'], 1, True)}]"', '(r[\'q3\'], 2, True)}]"'),
    ('irp_ui_panel.py', "(pm['median'], 1, True)} [{F.fmt_num(pm[", "(pm['median'], 1, False)} [{F.fmt_num(pm["),
    ('irp_ui_panel.py', "{F.fmt_num(100 * j['share_loss'], 0)} % der Instanzen ein Verlust). E", "{F.fmt_num(100 * j['share_loss'], 1)} % der Instanzen ein Verlust). E"),
    ('irp_ui_panel.py', '[\'E\'][\'gain\'], 1, True)} %)", delta_colo', '[\'E\'][\'gain\'], 1, False)} %)", delta_colo'),
    ('irp_ui_panel.py', "m(r['median'], 1, True)} [{F.fmt_num(r['", "m(r['median'], 1, False)} [{F.fmt_num(r['"),
    ('irp_ui_panel.py', "(r['q1'], 1, True)}; ", "(r['q1'], 2, True)}; "),
    ('irp_ui_panel.py', 'limit=12):', 'limit=13):'),
    ('irp_ui_panel.py', "t_num(100 * g['", "t_num(101 * g['"),
    ('irp_ui_panel.py', '], 1, True)}], "', '], 1, False)}], "'),
    ('irp_ui_panel.py', 'se"], 1, Fals', 'se"], 2, Fals'),
    ('irp_ui_panel.py', "(j['median'], 1, True)} %, in", "(j['median'], 2, True)} %, in"),
    ('irp_ui_panel.py', "ian'], 1, True)} %, in {", "ian'], 1, False)} %, in {"),
    ('irp_ui_panel.py', 'GHT + 60', 'GHT + 61'),
    ('irp_ui_panel.py', ' name != "R" e', ' name == "R" e'),
    ('irp_ui_panel.py', 'F.fmt_num(100 * (r["P_H', 'F.fmt_num(101 * (r["P_H'),
    ('irp_ui_panel.py', 'lumns[0].metr', 'lumns[1].metr'),
    ('irp_ui_panel.py', "(g['q1'], 1, True)}; ", "(g['q1'], 2, True)}; "),
    ('irp_ui_panel.py', 'il\'], 2)}",', 'il\'], 3)}",'),
    ('irp_ui_panel.py', 'se\'], 1)} %"', 'se\'], 2)} %"'),
    ('irp_ui_panel.py', '], 1, True)}]"),', '], 1, False)}]"),'),
    ('irp_ui_panel.py', "ops'] != 1 els", "ops'] == 1 els"),
    ('irp_ui_panel.py', 'ap"], 1, True', 'ap"], 2, True'),
    ('irp_ui_panel.py', 're"], 1) + " ', 're"], 2) + " '),
    ('irp_ui_panel.py', "'E']['diff'], True)} ({F.fmt_num", "'E']['diff'], False)} ({F.fmt_num"),
    ('irp_ui_panel.py', '], 1, False)', '], 1, True)'),
    ('irp_ui_panel.py', '\'P\'][\'gain\'], 1, True)} %."', '\'P\'][\'gain\'], 2, True)} %."'),
    ('irp_ui_panel.py', '["Q"] == marke', '["Q"] != marke'),
    ('irp_ui_panel.py', 'F.fmt_num(100 * (r["R"]', 'F.fmt_num(101 * (r["R"]'),
    ('irp_ui_panel.py', "_R'], 2)} → {", "_R'], 3)} → {"),
    ('irp_ui_panel.py', 'lumns[2].metr', 'lumns[3].metr'),
    ('irp_ui_panel.py', " 1)} %, in {F.fmt_num(100 * j['share_loss'], 0)", " 1)} %, in {F.fmt_num(101 * j['share_loss'], 0)"),
    ('irp_ui_panel.py', 'EIGHT + 60', 'EIGHT - 60'),
    ('irp_ui_panel.py', "{F.fmt_num(100 * j['share_loss'], 0)} % der Instanzen ein Verlust): e", "{F.fmt_num(100 * j['share_loss'], 1)} % der Instanzen ein Verlust): e"),
    ('irp_ui_panel.py', 'e "") + r["la', 'e "") - r["la'),
    ('irp_ui_panel.py', 'f (se == 0.0 a', 'f (se != 0.0 a'),
    ('irp_ui_panel.py', "(pm['q1'], 1, True)}; {F.fmt_num", "(pm['q1'], 1, False)}; {F.fmt_num"),
    ('irp_ui_panel.py', "m(-j['mean'], 1)} ± {F.fmt_nu", "m(-j['mean'], 2)} ± {F.fmt_nu"),
    ('irp_ui_panel.py', '], 1) + " %"}', '], 1) - " %"}'),
    ('irp_ui_panel.py', 'kups\'] != 1 else \'\'}"', 'kups\'] != 2 else \'\'}"'),
    ('irp_ui_panel.py', ' else 0.0, "Gew', ' else 0.1, "Gew'),
    ('irp_ui_panel.py', "se'], 1)} % m", "se'], 2)} % m"),
    ('irp_ui_panel.py', "(g['q3'], 1, True)}],", "(g['q3'], 2, True)}],"),
    ('irp_ui_panel.py', '["J"] - jr, r', '["J"] + jr, r'),
    ('irp_ui_panel.py', "m(r['q1'], 1, True)}; {F.fmt_num", "m(r['q1'], 1, False)}; {F.fmt_num"),
    ('irp_ui_panel.py', '["R"] - jo) /', '["R"] + jo) /'),
    ('irp_ui_panel.py', 'lumns[1].metr', 'lumns[2].metr'),
    ('irp_ui_panel.py', 'ps"], 1):', 'ps"], 2):'),
    ('irp_ui_panel.py', ' rule == "P" e', ' rule != "P" e'),
    ('irp_ui_panel.py', "ian'], 1, True)} %, Quar", "ian'], 1, False)} %, Quar"),
    ('irp_ui_panel.py', 'cv_gain"], 1, True),', 'cv_gain"], 1, False),'),
    ('irp_ui_panel.py', "rs']) != 1 els", "rs']) == 1 els"),
    ('irp_ui_panel.py', 't_num(100 * r["', 't_num(101 * r["'),
    ('irp_ui_panel.py', " g['share_loss'], 0)} % der Instanzen", " g['share_loss'], 1)} % der Instanzen"),
    ('irp_visualization.py', '= [(t + 1, c,', '= [(t - 1, c,'),
    ('irp_visualization.py', 'IES], visible=True, color="#4b5d', 'IES], visible=False, color="#4b5d'),
    ('irp_visualization.py', 'y=dict(type="data", array=[r["se"] for r in sel], visible=True, color="#4b5d75", thickness=1.2),', 'y=dict(type="data", array=[r["se"] for r in sel], visible=False, color="#4b5d75", thickness=1.2),'),
    ('irp_visualization.py', ' y0=i - 0.5, ', ' y0=i + 0.5, '),
    ('irp_visualization.py', 'float(min(xy[:,', 'float(max(xy[:,'),
    ('irp_visualization.py', ':, 1].min()))', ':, 1].max()))'),
    ('irp_visualization.py', 'ines", name=label, showlegend=False,', 'ines", name=label, showlegend=True,'),
    ('irp_visualization.py', 'xaxes=True, vert', 'xaxes=False, vert'),
    ('irp_visualization.py', '_days + 0.6],', '_days - 0.6],'),
    ('irp_visualization.py', 'ange(1, n + 1)], y=[f', 'ange(1, n - 1)], y=[f'),
    ('irp_visualization.py', '_yaxes(fixedrange=True)', '_yaxes(fixedrange=False)'),
    ('irp_visualization.py', '.0 for r in sel], visible=True, color="#4b5d75", thickne', '.0 for r in sel], visible=False, color="#4b5d75", thickne'),
    ('irp_visualization.py', ' v: v == 0)):', ' v: v != 0)):'),
    ('irp_visualization.py', 'ame"] == marke', 'ame"] != marke'),
    ('irp_visualization.py', ' - 1] + "…"', ' - 1] - "…"'),
    ('irp_visualization.py', 'limit - 1] + ', 'limit + 1] + '),
    ('irp_visualization.py', '] for i in range(1, n + 1)],', '] for i in range(1, n - 1)],'),
    ('irp_visualization.py', 'xaxes=True, row_', 'xaxes=False, row_'),
    ('irp_visualization.py', 'our"] - 1) % ', 'our"] + 1) % '),
    ('irp_visualization.py', '[r[2] or 0.0 f', '[r[2] and 0.0 f'),
    ('irp_visualization.py', ' size + 4], t', ' size - 4], t'),
    ('irp_visualization.py', 'text) <= limit', 'text) < limit'),
    ('irp_visualization.py', 'kers", name=label, showlegend=False,', 'kers", name=label, showlegend=True,'),
    ('irp_visualization.py', 'ays"] + 1))', 'ays"] - 1))'),
    ('irp_visualization.py', 'nge=[min(lo, 0.0) - 4, size + 4], sca', 'nge=[min(lo, 0.0) + 4, size + 4], sca'),
    ('irp_visualization.py', ' x1=j + 0.5, ', ' x1=j - 0.5, '),
    ('irp_visualization.py', ', 5.0 + p[2] ', ', 5.0 - p[2] '),
    ('irp_visualization.py', '     hoverinfo="skip", showlegend=False))', '     hoverinfo="skip", showlegend=True))'),
    ('irp_visualization.py', '_xaxes(fixedrange=True)', '_xaxes(fixedrange=False)'),
    ('irp_visualization.py', 'HT), (True, "Zel', 'HT), (False, "Zel'),
    ('irp_visualization.py', '["Q"] == marke', '["Q"] != marke'),
    ('irp_visualization.py', 'scale=False, hove', 'scale=True, hove'),
    ('irp_visualization.py', 'omers + 0.6],', 'omers - 0.6],'),
    ('irp_visualization.py', '\'])}" + ("<br', '\'])}" - ("<br'),
    ('irp_visualization.py', ' y1=i + 0.5, ', ' y1=i - 0.5, '),
    ('irp_visualization.py', 'ht=C.CHART_HEIGHT - 40, barmode="over', 'ht=C.CHART_HEIGHT + 40, barmode="over'),
    ('irp_visualization.py', 'ange(1, n + 1)], text', 'ange(1, n - 1)], text'),
    ('irp_visualization.py', 'ps"]] + [0]', 'ps"]] - [0]'),
    ('irp_visualization.py', 'EIGHT + 40, m', 'EIGHT - 40, m'),
    ('irp_visualization.py', 'ind"] == "Mitn', 'ind"] != "Mitn'),
    ('irp_pdf_export.py', '("- " + text)', '("- " - text)'),
    ('irp_pdf_export.py', 't_y() + heigh', 't_y() - heigh'),
    ('irp_pdf_export.py', 'eight > pdf.h', 'eight >= pdf.h'),
    ('irp_pdf_export.py', ' name != "R" e', ' name == "R" e'),
    ('irp_pdf_export.py', '], 1, True) if n', '], 1, False) if n'),
    ('irp_pdf_export.py', 'press=True):', 'press=False):'),
    ('irp_pdf_export.py', 'pdf.h - pdf.b', 'pdf.h + pdf.b'),
    ('irp_pdf_export.py', ' fill=True, new_', ' fill=False, new_'),
    ('tools/build_results.py', 'fac": 0.05, "kap', 'fac": 0.055, "kap'),
    ('tools/build_results.py', 'ame__ == "__ma', 'ame__ != "__ma'),
    ('tools/build_results.py', 'mma": 0.5}, "po', 'mma": 0.55}, "po'),
    ('tools/build_results.py', '{"N": 20, "Q":', '{"N": 21, "Q":'),
    ('tools/build_results.py', 'gv) > 1 else ', 'gv) > 2 else '),
    ('tools/build_results.py', 'ITS = 4', 'ITS = 5'),
    ('tools/build_results.py', '_keys=True, sepa', '_keys=False, sepa'),
    ('tools/build_results.py', '00.0, 6)', '00.0, 7)'),
    ('tools/build_results.py', 'eturn 0', 'eturn 1'),
    ('tools/build_results.py', '_hi": 14.0}', '_hi": 15.4}'),
    ('tools/build_results.py', 'bool) or x is ', 'bool) and x is '),
    ('tools/build_results.py', '_lo": 8.0, "tan', '_lo": 8.8, "tan'),
    ('tools/build_results.py', '{"H": 3, "gam', '{"H": 4, "gam'),
    ('tools/build_results.py', '(argv[0]) if ', '(argv[1]) if '),
    ('tools/build_results.py', 'c"] * 100.0, 6)', 'c"] * 110.0, 6)'),
    ('tools/build_results.py', '(argv[1]) if ', '(argv[2]) if '),
    ('tools/build_results.py', ' "Q": 300.0, "F":', ' "Q": 330.0, "F":'),
    ('tools/build_results.py', 'ze // 1024} KB, ', 'ze // 1025} KB, '),
    ('tools/build_results.py', 'alse) + "\\n"', 'alse) - "\\n"'),
    ('tools/build_results.py', 'lty"] - penal', 'lty"] + penal'),
    ('tools/build_results.py', 'argv) > 1 els', 'argv) >= 1 els'),
    ('tools/build_results.py', 'ppa": 1.0, "dep', 'ppa": 1.1, "dep'),
    ('tools/build_results.py', ' None or isins', ' None and isins'),
    ('tools/build_results.py', 'ascii=False) + "\\', 'ascii=True) + "\\'),
    ('tools/build_results.py', 'gma": 0.3, "pfa', 'gma": 0.33, "pfa'),
    ('tools/build_results.py', 'red": False, "tan', 'red": True, "tan'),
    ('tools/build_results.py', 'ode = True', 'ode = False'),
    ('tools/build_results.py', 'ty) < 1e-9, (nam', 'ty) < 0.0, (nam'),
    ('tools/build_results.py', 'alty) < 1e-9,', 'alty) <= 1e-9,'),
    ('tools/build_results.py', '.argv[1:]))', '.argv[2:]))'),
    ('tools/analyze.py', ' if q != "R"}', ' if q == "R"}'),
    ('tools/analyze.py', 'ax(), 100 * (pe', 'ax(), 101 * (pe'),
    ('tools/analyze.py', 't((sP > sR + ', 't((sP >= sR + '),
    ('tools/analyze.py', 'per = 100 * dif', 'per = 101 * dif'),
    ('tools/analyze.py', '- sR) <= 1e-9)', '- sR) < 1e-9)'),
    ('tools/analyze.py', 'ort") - tau *', 'ort") + tau *'),
    ('tools/analyze.py', ' neg[:25]:', ' neg[:26]:'),
    ('tools/analyze.py', '(argv[0]) if ', '(argv[1]) if '),
    ('tools/analyze.py', ').sum() / max(get(c, DE', ').sum() / min(get(c, DE'),
    ('tools/analyze.py', '(per, 75), np.', '(per, 76), np.'),
    ('tools/analyze.py', 't((sP < sR - ', 't((sP <= sR - '),
    ('tools/analyze.py', ' < sR - 1e-9)', ' < sR + 1e-9)'),
    ('tools/analyze.py', 'um(), 1)), "s', 'um(), 2)), "s'),
    ('tools/analyze.py', ', per.max(), 10', ', per.min(), 10'),
    ('tools/analyze.py', '", "n_routes").sum(), 1)),', '", "n_routes").sum(), 2)),'),
    ('tools/analyze.py', 'ode = True', 'ode = False'),
    ('tools/analyze.py', '(per, 25)), "m', '(per, 26)), "m'),
    ('tools/analyze.py', '(per, 25), np.', '(per, 26), np.'),
    ('tools/analyze.py', '(per, 90), per', '(per, 91), per'),
    ('tools/analyze.py', ' * (per < 0).mean()))', ' * (per < 1).mean()))'),
    ('tools/analyze.py', ').sum() / max(get(c, EA', ').sum() / min(get(c, EA'),
    ('tools/analyze.py', 'tq] < 0:', 'tq] < 1:'),
    ('tools/analyze.py', 't(per.max()), "', 't(per.min()), "'),
    ('tools/analyze.py', 'ppend(100 * bg.', 'ppend(101 * bg.'),
    ('tools/analyze.py', 'per)), "q1": float(np.percentile(per, 25)),', 'per)), "q1": float(np.percentile(per, 26)),'),
    ('tools/analyze.py', ' (per < 0).me', ' (per <= 0).me'),
    ('tools/analyze.py', ' = JR - JP', ' = JR + JP'),
    ('tools/analyze.py', 'ean": 100 * dif', 'ean": 101 * dif'),
    ('tools/analyze.py', 'se"], 100 * d["', 'se"], 101 * d["'),
    ('tools/analyze.py', 'R[te] - J_arr', 'R[te] + J_arr'),
    ('tools/analyze.py', 'ean"] < 0)', 'ean"] <= 0)'),
    ('tools/analyze.py', 'R) <= 1e-9).mean', 'R) <= 0.0).mean'),
    ('tools/analyze.py', 'at((per < 0).mean())}', 'at((per < 1).mean())}'),
    ('tools/analyze.py', 'bs(sP - sR) <', 'bs(sP + sR) <'),
    ('tools/analyze.py', 't_R"] < 200]', 't_R"] <= 200]'),
    ('tools/analyze.py', 'R[tr] - J_arr', 'R[tr] + J_arr'),
    ('tools/analyze.py', 'ff < -1e-9).mean', 'ff < -0.0).mean'),
    ('tools/analyze.py', 'ple = max(PPOL,', 'ple = min(PPOL,'),
    ('tools/analyze.py', 's(y))[0, 1])', 's(y))[1, 1])'),
    ('tools/analyze.py', '(diff < -1e-9', '(diff <= -1e-9'),
    ('tools/analyze.py', '.argv[1:]))', '.argv[2:]))'),
    ('tools/analyze.py', '(per, 75)), "s', '(per, 76)), "s'),
    ('tools/analyze.py', 'eturn 0', 'eturn 1'),
    ('tools/analyze.py', 'ame__ == "__ma', 'ame__ != "__ma'),
    ('tools/analyze.py', 'ndent=1, defa', 'ndent=2, defa'),
    ('tools/analyze.py', ' sR - 1e-9).mean', ' sR - 0.0).mean'),
    ('tools/analyze.py', 'R"] < 200]', 'R"] < 201]'),
    ('tools/analyze.py', 'n"] < 0)', 'n"] < 1)'),
    ('tools/analyze.py', ' > sR + 1e-9)', ' > sR - 1e-9)'),
    ('tools/analyze.py', '(per, 90)), "m', '(per, 91)), "m'),
    ('tools/analyze.py', 'ing") + pen *', 'ing") - pen *'),
    ('tools/analyze.py', ' z: z[2])', ' z: z[3])'),
    ('tools/analyze.py', '= sum(1 for c', '= sum(2 for c'),
    ('tools/analyze.py', 'estq] < 0:', 'estq] <= 0:'),
    ('tools/analyze.py', ') % 2 == 0', ') % 2 != 0'),
    ('tools/analyze.py', '), "q3": float(np.percentile(per, 75)),', '), "q3": float(np.percentile(per, 76)),'),
    ('tools/analyze.py', ' 2 == 0', ' 2 == 1'),
    ('tools/analyze.py', 'per = 100 * (JR', 'per = 101 * (JR'),
    ('tools/analyze.py', 'n"] < 0:', 'n"] < 1:'),
    ('tools/analyze.py', 'stq = max(cands', 'stq = min(cands'),
    ('tools/oracle_run.py', 'e"] - 1e-6, ("Re', 'e"] - 1e-06, ("Re'),
    ('tools/oracle_run.py', ' row[name + "_routing', ' row[name - "_routing'),
    ('tools/oracle_run.py', 'flush=True)', 'flush=False)'),
    ('tools/oracle_run.py', 'argv) > 0 els', 'argv) >= 0 els'),
    ('tools/oracle_run.py', 're(JR - JO > ', 're(JR + JO > '),
    ('tools/oracle_run.py', 't"] > 0 and r', 't"] > 1 and r'),
    ('tools/oracle_run.py', 'ime() - t0)', 'ime() + t0)'),
    ('tools/oracle_run.py', 'st_ok=True)', 'st_ok=False)'),
    ('tools/oracle_run.py', 'tus"] == "OPTI', 'tus"] != "OPTI'),
    ('tools/oracle_run.py', '(gap, 25)), "q', '(gap, 26)), "q'),
    ('tools/oracle_run.py', ', gap.max(),', ', gap.min(),'),
    ('tools/oracle_run.py', '(8.0, 0.25, 0.0)', '(8.0, 0.275, 0.0)'),
    ('tools/oracle_run.py', '  sum(1 for r', '  sum(2 for r'),
    ('tools/oracle_run.py', '"R": (0.0, 0.5,', '"R": (0.1, 0.5,'),
    ('tools/oracle_run.py', '(), gain.std(ddof=1) / np.sqrt(len(ga', '(), gain.std(ddof=2) / np.sqrt(len(ga'),
    ('tools/oracle_run.py', '= (JR - v) / ', '= (JR + v) / '),
    ('tools/oracle_run.py', 'ort"] > 0 and', 'ort"] >= 0 and'),
    ('tools/oracle_run.py', 'name] >= row["', 'name] > row["'),
    ('tools/oracle_run.py', '0.0, 0.5, 0.0), "P_H3_g', '0.0, 0.5, 0.1), "P_H3_g'),
    ('tools/oracle_run.py', '50": (3.0, 0.5,', '50": (3.3, 0.5,'),
    ('tools/oracle_run.py', 'L1": (0.0, 0.5,', 'L1": (0.1, 0.5,'),
    ('tools/oracle_run.py', '= sum(1 for r', '= sum(2 for r'),
    ('tools/oracle_run.py', '(0.0, 0.5, 0.0)', '(0.0, 0.55, 0.0)'),
    ('tools/oracle_run.py', ' - JO > 1e-9,', ' - JO >= 1e-9,'),
    ('tools/oracle_run.py', '[name + "_sha', '[name - "_sha'),
    ('tools/oracle_run.py', ' row[name + "_routes"', ' row[name - "_routes"'),
    ('tools/oracle_run.py', '(), gapO.std(ddof=1) / np.sqrt(len(ga', '(), gapO.std(ddof=2) / np.sqrt(len(ga'),
    ('tools/oracle_run.py', '(argv[0]) if ', '(argv[1]) if '),
    ('tools/oracle_run.py', 'ame__ == "__ma', 'ame__ != "__ma'),
    ('tools/oracle_run.py', ' seed=1)', ' seed=2)'),
    ('tools/oracle_run.py', '9, JR - JO, n', '9, JR + JO, n'),
    ('tools/oracle_run.py', ' else 120.0', ' else 132.0'),
    ('tools/oracle_run.py', '25": (8.0, 0.25', '25": (8.8, 0.25'),
    ('tools/oracle_run.py', '[name + "_gai', '[name - "_gai'),
    ('tools/oracle_run.py', '(POL) + ["J_o', '(POL) - ["J_o'),
    ('tools/confirm_default.py', '{"Q": 100.0}, "q6', '{"Q": 110.0}, "q6'),
    ('tools/confirm_default.py', '(per, 25)), "q', '(per, 26)), "q'),
    ('tools/confirm_default.py', 'fac", 0.05)', 'fac", 0.055)'),
    ('tools/confirm_default.py', 'fac * 100.0', 'fac * 110.0'),
    ('tools/confirm_default.py', 'range(200, 300)', 'range(201, 300)'),
    ('tools/confirm_default.py', ' days=120, tau=', ' days=121, tau='),
    ('tools/confirm_default.py', 'ean"] - sweep', 'ean"] + sweep'),
    ('tools/confirm_default.py', 'n": float(100 * diff.me', 'n": float(101 * diff.me'),
    ('tools/confirm_default.py', 'e": float(100 * diff.st', 'e": float(101 * diff.st'),
    ('tools/confirm_default.py', '(ddof=1) / ma', '(ddof=2) / ma'),
    ('tools/confirm_default.py', 'DS, H=3.0, gamm', 'DS, H=3.3, gamm'),
    ('tools/confirm_default.py', 't(per.max()), "', 't(per.min()), "'),
    ('tools/confirm_default.py', '.argv[1:]))', '.argv[2:]))'),
    ('tools/confirm_default.py', 'lust {100 * swe', 'lust {101 * swe'),
    ('tools/confirm_default.py', 'cell, 3, 0.5)', 'cell, 4, 0.5)'),
    ('tools/confirm_default.py', ' "Q": 300.0}}', ' "Q": 330.0}}'),
    ('tools/confirm_default.py', 'eturn 0', 'eturn 1'),
    ('tools/confirm_default.py', '{"F": 1, "Q":', '{"F": 2, "Q":'),
    ('tools/confirm_default.py', ' argv or list(', ' argv and list('),
    ('tools/confirm_default.py', '(per, 75)), "m', '(per, 76)), "m'),
]
